apiVersion: v1
kind: Pod
metadata: 
  name: sapan-pod1
  namespace: default
spec: 
  containers:
  - image: nginx:alpine
    imagePullPolicy: IfNotPresent
    name: vishal-nginx
    ports: 
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata: 
  name: sapan-pod2
  namespace: default
spec: 
  containers:
  - image: lscr.io/linuxserver/chrome:latest
    imagePullPolicy: IfNotPresent
    name: vishal-chrome
    ports: 
    - containerPort: 3000


---

apiVersion: v1
kind: Pod
metadata: 
  name: sapan-pod3
  namespace: default
spec: 
  containers:
  - image: careerdeveloper1/yt
    imagePullPolicy: IfNotPresent
    name: vishal-nginx
    ports: 
    - containerPort: 80
