FROM nginx:alpine

# Copy your static HTML to Nginx’s default site directory
COPY index.html /usr/share/nginx/html/index.html

# Expose Nginx port
EXPOSE 80

# Nginx starts automatically, no need for CMD
